---
# https://stackoverflow.com/questions/63612155/how-do-i-trigger-a-scheduled-action-on-a-specific-branch/63612525#63612525
name: Test deployment
on:
  # run once a day
  schedule:
    - cron: '0 10 * * 0-6'
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          ref: ga-workflow-schedule-only

